package koharia.source.komga

typealias LibraryConnectionProfilesScreen = koharia.connection.ui.LibraryConnectionProfilesScreen
typealias KomgaServerProfilesScreen = koharia.connection.ui.LibraryConnectionProfilesScreen
